### ISSUE TITLE
 undefined symbol

### ISSUE THREAD

**Issue by shiyezia** [nextfoam/baram#38]
Hello.

When I try to use my own solver ,  I encountered an error:   the  dynamic libraries have undefined symbol.

Can I use my own sovler with baram？How can I do it？

thanks！

**Comment by jiban** [comment]
Hello, @shiyezia!
Thank you for showing interest in Baram.
Of course, you can use your own solver, but it should be compiled in the context of Baram's solver engine.
The engine, we call it _OpenFOAM-N_, is a variant of OpenFOAM and is naturally open source.
If you need it, I will upload it somewhere so that you can download and try.
Thank you.
