### ISSUE TITLE
Mesh export doesn't finish in BaramMesh

### ISSUE THREAD

**Issue by MTODC** [nextfoam/baram#93]
**Describe the bug**
As reported in Issue #81 , but in Windows 11 OS. The export process is stucked in "Processing Cell Zones", I wait 1 hour before killing the process.

**To Reproduce**
Link for the BaramMesh folder: https://drive.google.com/file/d/13uig3SyHgURKyd-T4qW7YAMS1-nibWNO/view?usp=sharing

**Screenshots**
![image](https://github.com/user-attachments/assets/ecf5cafb-d0b1-4007-b16c-4f8553faae9d)

**Desktop:**
 - OS: Windows 11
 - Version 24.2.1

**Comment by jiban** [comment]
Dear @MTODC,
I've looked into your case and found a root cause of it.
You had configured two regions in *Region* step, but only one mesh region was identified by *snappyHexMesh*.
The process in *export* step failed because the mesh had only one region while it expected two regions.

It was caused by a leak between *Inside_surf* and *Duct*.
As you may know every boundary in the geometry should be tight.
For example, following is a capture of STL files (*Inlet* and *Duct*).

![image](https://github.com/user-attachments/assets/026a836a-e336-4f82-bf4a-7ddfa6c04dce)

Every vertex of the two surfaces meets each other exactly at the same point.
There is no leakage (hole).

On the other hand, following is a capture of *Inside_surf* and *Duct*.

![image](https://github.com/user-attachments/assets/0926c185-712f-44f4-92d0-29ec1a31a97a)

There are leaks between the two surfaces.
This is a simplified drawing.

![image](https://github.com/user-attachments/assets/25e0b942-0a13-4c53-9c7f-20c11b836d2c)

I think it would be better if BaramMesh could detect that generated mesh had only one region and show a warning message.
I will study if there is a way to figure out it.

In the mean time, could you make the surfaces tight and try again?

Best regards,
Jake

**Comment by MTODC** [comment]
@jiban now it works, thank you!!
